=== vikramsingh1985/java_workspace/xml_render_parse-master/Parsing XML/Addressd.dtd
<!ELEMENT addressbook (contact)+>
<!ELEMENT contact (name, address+, city, state, zip, phone, email, web, company)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT phone (voice, fax?)>
<!ELEMENT voice (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT company (#PCDATA)>

=== vikramsingh1985/java_workspace/xml_render_parse-master/Parsing XML/addressbook1.xml
<?xml version = "1.0" ?>
<!DOCTYPE addressbook SYSTEM "Addressd.dtd" >
<addressbook>
	<contact>
		<Name> A.N. Mukerjee </Name>
		<address>SDF Bldgs 219-222
		</address>
		<city>salt lake</city>
		<state>WB</state>
		<zip>700091</zip>
		<phone>
		<voice>033-3692287</voice>
		<fax>033-3628638</fax>
		</phone>
		<email>drall@indiatimes.com 						</email>
		<web> http://www.indiatimes.com 					</web>
		<company>TCS</company>
	</contact>
</addressbook>

=== vikramsingh1985/java_workspace/xml_render_parse-master/Parsing XML/addressbook.xml
<?xml version = "1.0" ?>
 <?xml-stylesheet type = "text/css" href = "Addressc.css" ?>
 <!DOCTYPE addressbook SYSTEM "Addressd.dtd" > 

<addressbook>
  <contact>
	<Name> A Mukerjee </Name>
	<address>SDF Bldgs 219-222</address>
	<city>salt lake</city>
	<state>WB</state>
	<zip>700091</zip>
	<phone>
	  <voice>033-3692287</voice>
	  <fax>033-3628638</fax>
	</phone>
	<email>drall@indiatimes.com</email>
	<web>http://www.indiatimes.com</web>
	<company>TCS</company>
   </contact>

  <contact>
	<name> Mukerjee </name>
	<address>SDF 219-222</address>
	<city> lake</city>
	<state>MP</state>
	<zip>700001</zip>
	<phone>
	  <voice>023-3692287</voice>
          <fax>043-3628638</fax>
	</phone>
	<email>drallpk@indiatimes.com</email>
	<web>http://www.indiatimes.com</web>
	<company>Indiatimes</company>
   </contact>

<contact>
<Name> Manish </Name>
<address>Rohini</address>
<city>salt lake</city>
<state>Delhi</state>
<zip>110091</zip>
<phone>
<voice>011-2312122</voice>
</phone>
<email>manish@indiatimes.com</email>
<web>http://www.indiatimes.com</web>
<company>Ducat</company>
</contact>



</addressbook>
