=== vikramsingh1985/java_workspace/xml_render_parse-master/Parsing XML/SAX/students.dtd
<!ELEMENT students  (student+)>
<!ELEMENT student (id,name,fee)>
<!ATTLIST student  course (J2ee | .Net | Sqt) #REQUIRED > 
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT fee (#PCDATA)>

=== vikramsingh1985/java_workspace/xml_render_parse-master/Parsing XML/SAX/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd" >
<students>
  <student course = "J2ee" >
    <id>1001</id>
    <name>Raj</name>
    <fee>10000</fee>
  </student>
<student course = ".Net" >
    <id>1002</id>
    <name>Raman</name>
    <fee>7000</fee>
  </student>

</students>
